using System.Collections.Generic;
using UnityEngine;

namespace MilitaryShogi.Game
{
    public enum Sfx { Select, Place, Clash, Topple, End }

    /// <summary>
    /// Short wooden sound effects (generated by Tools/AudioGen, no external material). Honors the
    /// 効果音 ON/OFF and volume settings immediately. Every request is logged with its time so the
    /// auto-test can check that sounds line up with the matching visual event at every speed.
    /// </summary>
    public sealed class AudioDirector : MonoBehaviour
    {
        /// <summary>Delay from the start of the topple clip to its main "falls on the board" hit.</summary>
        public const float ToppleImpactOffset = 0.075f;

        public struct Entry
        {
            public Sfx Kind;
            public float Time;
            public bool Audible;
        }

        private readonly Dictionary<Sfx, AudioClip[]> clips = new Dictionary<Sfx, AudioClip[]>();
        private AudioSource source;
        private GameSettings settings;
        private int variant;
        public readonly List<Entry> Log = new List<Entry>();
        public float CurrentVolume { get { return source != null ? source.volume : 0f; } }

        public void Initialise(GameSettings settings)
        {
            this.settings = settings;
            source = gameObject.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.spatialBlend = 0f;
            clips[Sfx.Select] = Load("sfx_select");
            clips[Sfx.Place] = Load("sfx_place_1", "sfx_place_2", "sfx_place_3");
            clips[Sfx.Clash] = Load("sfx_clash_1", "sfx_clash_2");
            clips[Sfx.Topple] = Load("sfx_topple");
            clips[Sfx.End] = Load("sfx_end");
        }

        private static AudioClip[] Load(params string[] names)
        {
            var list = new List<AudioClip>();
            foreach (var n in names)
            {
                var c = Resources.Load<AudioClip>("Audio/" + n);
                if (c == null) Debug.LogError("Missing sound Resources/Audio/" + n);
                else list.Add(c);
            }
            return list.ToArray();
        }

        public bool HasAllClips
        {
            get
            {
                foreach (var kv in clips) if (kv.Value.Length == 0) return false;
                return clips.Count == 5;
            }
        }

        private void Update()
        {
            if (source != null && settings != null) source.volume = settings.SfxOn ? settings.SfxVolume / 100f : 0f;
        }

        public void Play(Sfx kind)
        {
            bool audible = settings != null && settings.SfxOn && settings.SfxVolume > 0;
            Log.Add(new Entry { Kind = kind, Time = Time.time, Audible = audible });
            if (Log.Count > 4000) Log.RemoveRange(0, 1000);
            if (!audible || source == null) return;
            AudioClip[] set;
            if (!clips.TryGetValue(kind, out set) || set.Length == 0) return;
            var clip = set[variant++ % set.Length];   // presentation-only rotation, no game randomness
            source.volume = settings.SfxVolume / 100f;
            source.PlayOneShot(clip);
        }
    }
}
